### ISSUE TITLE
contributing.md : TODO

### ISSUE THREAD

**Issue by VLEFF** [filebrowser/community#3]
Hi there!

I'm using filebrowser for some days now, and it's great! I wrote a feature request last weak, and since I have some time, I would be happy to implement it, but I'm actually a little stuck in the process of running my own version. 
So is there somewhere some kind of guidelines to do so?

EDIT : Well, I just saw the pending MR for this, so this issue is kind of irrelevant, I close it =)

**Comment by hacdias** [comment]
Hey @VLEFF!

Sorry for not having updated Contributing.md. We are trying to update the build process, but due to some technical difficulties it hasn't been possible yet.

Any way, right now, you need to have Go, Git and Nodejs.

So:

- `go get -u github.com/filebrowser/filebrowser/cmd/filebrowser`
- `git clone https://github.com/filebrowser/frontend`

On `frotend`:

- `yarn install && yarn link`
- `yarn dev`

On `GOPATH/src/github.com/filebrowser/filebrowser`:

- Delete `rice-box.go`
- `yarn install && yarn link filebrowser-frontend`

Now, go to wherever you want to serve files and just run:

- `go install github.com/filebrowser/filebrowser/cmd/filebrowser && filebrowser --port 8080`

When you change frontend assets, you'll just need to reload the page. If you change Go assets, you'll need to re-build the package with the previous command.

Hope it helps!

**Comment by VLEFF** [comment]
Thanks! 
It works like a charm ;)

See you in my future PR =p

**Comment by VLEFF** [comment]
I spoke a little bit too fast, I have filebrowser already installed on my machine with 
`wget -qO- https://filebrowser.github.io/get.sh | bash`

so when I run filebrowser --port 8080, it runs this version, not the dev one that I just cloned =o

**Comment by VLEFF** [comment]
Everything sets up, great reactivity, thanks a lot =)
